services:
  - type: web
    name: bookmyshow
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bookmyshow.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bookmyshow.settings
      - key: DATABASE_URL
        value: postgresql://django_bookmyseat_bysaurav_user:MC5kqOsQ0WuvcII2qSVRq82mUhgGCoAf@dpg-d1a8uah5pdvs73ajhko0-a.oregon-postgres.render.com/django_bookmyseat_bysaurav )
